### ISSUE TITLE
"port.service.cpe" returns all CPEs, not just those for that specific port/service

### ISSUE THREAD

**Issue by dprobinson** [sophsec/ruby-nmap#37]
"port.service.cpe" returns all CPEs, not just those for that specific port/service.

**Comment by postmodern** [comment]
This should be fixed in master now.

<pre>
$ ruby -I lib cpebug.rb 
[127.0.0.1]
Open port 8000/tcp
Service: http
CPEs for port: cpe:/a:igor_sysoev:nginx:1.0.0
-----
Open port 8001/tcp
Service: http
CPEs for port: cpe:/a:apache:http_server:2.2.3
-----
Open port 123/udp
Service: ntp
CPEs for port: 
-----
</pre>
